# ==========================================
# C Library Makefile
# ==========================================

# --- Configuration ---
# Name of the output library
LIB_NAME = date.a

# Compiler and Standard
CC = gcc
STD = -std=c99

# Directories
SRC_DIR = src
INC_DIR = include
BUILD_DIR = build
LIB_DIR = lib
TEST_DIR = tests
BIN_DIR = bin

# Flags
# -I creates the include path
# -MMD -MP creates dependency files (.d) to track header changes
CFLAGS = $(STD) -Wall -Wextra -Werror -pedantic -I$(INC_DIR) -MMD -MP

# Source and Object files
SRCS = $(wildcard $(SRC_DIR)/*.c)
OBJS = $(patsubst $(SRC_DIR)/%.c, $(BUILD_DIR)/%.o, $(SRCS))

# Test files
TEST_SRCS = $(wildcard $(TEST_DIR)/*.c)
TEST_BIN = $(BIN_DIR)/test_runner

# --- Targets ---

.PHONY: all clean debug release test directories

# Default target (Release build)
all: release

# 1. Core Build (Release)
# Optimized, no debug symbols
release: CFLAGS += -O2
release: $(LIB_DIR)/$(LIB_NAME)

# 2. Debug Build
# Debug symbols, no optimization, defines DEBUG macro
debug: CFLAGS += -g -O0 -DDEBUG
debug: $(LIB_DIR)/$(LIB_NAME)

# Link the library (Static Archive)
$(LIB_DIR)/$(LIB_NAME): directories $(OBJS)
	@echo "Archiving library..."
	ar rcs $@ $(OBJS)
	@echo "Library created at $@"

# Compile source files into object files
$(BUILD_DIR)/%.o: $(SRC_DIR)/%.c
	@echo "Compiling $<..."
	$(CC) $(CFLAGS) -c $< -o $@

# 3. Test Build
# Compiles tests, links against the library, and runs the executable
test: debug $(TEST_BIN)
	@echo "Running Tests..."
	./$(TEST_BIN)

$(TEST_BIN): $(TEST_SRCS) $(LIB_DIR)/$(LIB_NAME)
	@mkdir -p $(BIN_DIR)
	$(CC) $(CFLAGS) $(TEST_SRCS) -L$(LIB_DIR) -l:$(LIB_NAME) -o $@

# 4. Clean Action
clean:
	@echo "Cleaning up..."
	rm -rf $(BUILD_DIR) $(LIB_DIR) $(BIN_DIR)

# Helper to create directories
directories:
	@mkdir -p $(BUILD_DIR) $(LIB_DIR)

# Include dependency files (generated by -MMD)
-include $(OBJS:.o=.d)
